import ctypes
def enum(**A):return type('Enum',(),A)
MOUSE_CLICK=enum(LEFT_DOWN=1,LEFT_UP=2,RIGHT_DOWN=4,RIGHT_UP=8,SCROLL_CLICK_DOWN=16,SCROLL_CLICK_UP=32,BACK_DOWN=64,BACK_UP=128,FOWARD_DOWN=256,FOWARD_UP=512,SCROLL_DOWN=4287104000,SCROLL_UP=7865344)
KEYBOARD_INPUT_TYPE=enum(KEYBOARD_DOWN=0,KEYBOARD_UP=1)
class RZCONTROL:
        def __init__(A,dll_path):B=None;A.dll=ctypes.WinDLL(dll_path);A.init=A.dll.init;A.init.argtypes=[];A.init.restype=ctypes.c_bool;A.mouse_move=A.dll.mouse_move;A.mouse_move.argtypes=[ctypes.c_int,ctypes.c_int,ctypes.c_bool];A.mouse_move.restype=B;A.mouse_click=A.dll.mouse_click;A.mouse_click.argtypes=[ctypes.c_int];A.mouse_click.restype=B;A.keyboard_input=A.dll.keyboard_input;A.keyboard_input.argtypes=[ctypes.c_short,ctypes.c_int];A.keyboard_input.restype=B
        def init(A):'finds the symbolic link that contains name RZCONTROL and opens a handle to the respective device\n\n        Returns:\n            bool: valid device handle\n        ';return A.init()
        def mouse_move(A,x,y,from_start_point):"if going from point, x and y will be the offset from current mouse position\n\t       otherwise it will be a number in range of 1 to 65536, where 1, 1 is top left of screen\n\t       if using multiple monitors the input values remain the same, but outcome different, i just don't recommend bothering with this bs\n\t       note: x and/or y can not be 0 unless going from start point\t\n\n        Args:\n            x (int)\n            y (int)\n            from_start_point (bool)\n        ";A.mouse_move(x,y,from_start_point)
        def mouse_click(A,click_mask):'\n        Args:\n            click_mask (MOUSE_CLICK):\n        ';A.mouse_click(click_mask)
        def keyboard_input(A,scan_code,up_down):'\n        Args:\n            scan_code (short): https://www.millisecond.com/support/docs/current/html/language/scancodes.htm\n            up_down (KEYBOARD_INPUT_TYPE): _description_\n        ';A.keyboard_input(scan_code,up_down)